package bundle

import (
	"os"
	"path/filepath"

	"github.com/StevenACoffman/gnosis/internal/ontology"
	"github.com/StevenACoffman/gnosis/internal/schema"
	"github.com/StevenACoffman/skillet/atomicfile"
	"github.com/StevenACoffman/skillet/errs"
)

// SchemaFile is the agent-facing schema document (§5.7), at the bundle root and
// committed.
const SchemaFile = "AGENTS.md"

// SchemaSibling is where the generated text goes when the committed file carries no
// markers.
//
// Beside it rather than over it, which is §5.7.1's fail-closed rule: a file predating
// this tool was not written under its contract, so its existence is not consent.
const SchemaSibling = "AGENTS.generated.md"

// schemaPreamble is the document's opening, written once when there is no file at all.
//
// It is outside every marker on purpose, so the first thing a reader is told is that
// the rest of the file is theirs — and so this sentence is the first thing gnosis stops
// maintaining. A preamble inside a region would be prose the generator owned, which is
// the one thing §5.7 says it must not write.
const schemaPreamble = "# Agent Schema\n" +
	"\n" +
	"How this corpus is organised, for an agent arriving with a question.\n" +
	"\n" +
	"The regions between `gnosis:begin` and `gnosis:end` markers are generated by " +
	"`gnosis schema` and will be overwritten. Everything outside them is yours: " +
	"gnosis preserves it byte for byte and never re-wraps or tidies it."

// MarkedDoc is what maintaining one marked root document would do.
//
// It is a *plan* rather than a result: computing it writes nothing, so a caller can
// report drift under `--check` and apply the same value later without the two paths
// being able to disagree — the argument §4.6.2 makes for preview and apply being one
// command, applied to a file.
type MarkedDoc struct {
	// Path is bundle-relative: the document itself, or the sibling when the committed
	// file carries no markers.
	Path string

	// Outcome is what the merge did, or why it refused.
	Outcome schema.Outcome

	// Stale reports whether writing Content would change anything.
	Stale bool

	// Content is the text to write. Meaningful only when Outcome permits a write.
	Content string
}

// PlanSchemaDoc works out what the schema document should contain.
//
// Requires: bundleDir is a bundle root, which need not exist; commands is this
// binary's command list, which only a `cmd` package can supply.
// Ensures: writes nothing. An absent ontology yields no types rather than an error —
// `doctor` reports that absence, and failing here would report it twice and leave the
// caller with neither a document nor a diagnosis.
//
// The command list is a parameter because `internal/` cannot import `cmd/` and must
// not: the binary describing itself is the point, and a list maintained here would be
// the second place to remember that §12's generated-table argument is about.
func PlanSchemaDoc(bundleDir string, commands []schema.CommandEntry) (MarkedDoc, error) {
	const op = "bundle.PlanSchemaDoc"

	types, err := declaredTypes(op, bundleDir)
	if err != nil {
		return MarkedDoc{}, err
	}
	return planMarked(op, bundleDir, SchemaFile, SchemaSibling, schemaPreamble,
		schema.SchemaRegions(types, commands))
}

// planMarked is the marker contract applied to one root document.
//
// Requires: name and sibling are bundle-relative; regions are what the document should
// carry.
// Ensures: writes nothing. An absent file is generated whole; an unmarked one yields
// the sibling; a malformed one yields no content at all.
//
// Shared by both documents rather than written twice, because §5.7.1's rules are a
// property of the *class* of reserved root files, and a second copy is where the two
// would drift — one gaining the unterminated-marker refusal and the other not.
func planMarked(op, bundleDir, name, sibling, preamble string, regions []schema.Region,
) (MarkedDoc, error) {
	existing, err := os.ReadFile(filepath.Join(bundleDir, filepath.FromSlash(name)))
	if err != nil {
		if !os.IsNotExist(err) {
			return MarkedDoc{}, &errs.Error{Op: op, Err: err}
		}
		// No file at all is not the unmarked case: there is no prose to protect, and
		// refusing would leave a corpus with no document and no way to get one.
		return MarkedDoc{
			Path:    name,
			Outcome: schema.OutcomeMerged,
			Stale:   true,
			Content: schema.Render(preamble, regions),
		}, nil
	}

	merged, outcome := schema.Merge(string(existing), regions)
	out := MarkedDoc{Path: name, Outcome: outcome, Content: merged}
	switch outcome {
	case schema.OutcomeUnmarked:
		out.Path, out.Stale = sibling, true
	case schema.OutcomeMerged:
		out.Stale = merged != string(existing)
	case schema.OutcomeMalformed, schema.OutcomeUnwritten:
		out.Content = ""
	}
	return out, nil
}

// WriteMarkedDoc writes a planned marked document.
//
// Requires: the writer holds the lock; doc came from PlanSchemaDoc and its outcome
// permits a write.
// Ensures: nothing is written for a plan that is not stale, so a second run is a no-op
// and `--check` and this cannot disagree about whether there was work.
//
// **The lock is why this is a method, and the first version of `schema` did not take
// it.** `AGENTS.md` is committed and at the bundle root, so two processes writing it
// would interleave — §4.6's rule that the writer owns the bundle rather than merely the
// database, which `Writer.Log` already follows for the one other committed root file a
// command writes.
func (w *Writer) WriteMarkedDoc(doc *MarkedDoc) error {
	const op = "bundle.Writer.WriteMarkedDoc"

	if err := w.held(op); err != nil {
		return err
	}
	if !doc.Stale {
		return nil
	}
	full := filepath.Join(w.dir, filepath.FromSlash(doc.Path))
	if err := atomicfile.WriteFile(full, []byte(doc.Content), 0o640); err != nil {
		return &errs.Error{Op: op, Err: err}
	}
	return nil
}

// declaredTypes reads the corpus's vocabulary down to what the schema document shows.
func declaredTypes(op, bundleDir string) ([]schema.TypeEntry, error) {
	raw, err := os.ReadFile(filepath.Join(bundleDir, ontology.FileName))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, &errs.Error{Op: op, Err: err}
	}
	o, err := ontology.Load(raw)
	if err != nil {
		return nil, &errs.Error{Code: errs.EINVALID, Op: op, Err: err}
	}
	out := make([]schema.TypeEntry, 0, len(o.Types))
	for i := range o.Types {
		t := &o.Types[i]
		entry := schema.TypeEntry{Key: t.Key.String(), Desc: t.Desc}
		if t.Deprecated != nil {
			// The message rather than a bare "deprecated": §5.8.1's announcement *is*
			// the message, and dropping it leaves an author told to stop with no
			// account of what to do instead.
			entry.Deprecated = t.Deprecated.Message
		}
		out = append(out, entry)
	}
	return out, nil
}
